import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Header from '../components/Header';
const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Cleveland Stargazers</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main>
        <h1 className="text-3xl font-bold underline">Hello world!</h1>
        <h2>stuff</h2>
      </main>
    </div>
  );
};

export default Home;
